### ISSUE TITLE
I just can not sign in...

### ISSUE THREAD

**Issue by Haidafraid** [chipx86/cloudplaya#10]
IMHO this has probably something to to with the fact that I am a German user... at least the amazon.com site redirects me to amazon.de when I try to launch https://www.amazon.com/gp/dmusic/mp3/player within firefox.

Is there anything to change to use cloudplaya with my german account?

this is the error I get whenever I try to start cloudplaya with
cloudplaya authenticate --username me! --password mine 

Traceback (most recent call last):
  File "/usr/local/bin/cloudplaya", line 9, in <module>
    load_entry_point('cloudplaya==0.2', 'console_scripts', 'cloudplaya')()
  File "/usr/local/lib/python2.6/dist-packages/cloudplaya-0.2-py2.6.egg/cloudplaya/main.py", line 298, in main
    command.run()
  File "/usr/local/lib/python2.6/dist-packages/cloudplaya-0.2-py2.6.egg/cloudplaya/main.py", line 41, in run
    self.options.password):
  File "/usr/local/lib/python2.6/dist-packages/cloudplaya-0.2-py2.6.egg/cloudplaya/client.py", line 95, in authenticate
    browser.select_form(name="signIn")
  File "/usr/local/lib/python2.6/dist-packages/mechanize-0.2.5-py2.6.egg/mechanize/_mechanize.py", line 524, in select_form
    raise FormNotFoundError("no form matching "+description)
mechanize._mechanize.FormNotFoundError: no form matching name 'signIn'

**Comment by xiconet** [comment]
Same problem here

**Comment by xiconet** [comment]
Guess we'll have to edit the code manually.
BTW, It seems that the code I got using "pip install" (easy_install failed) is different from the GitHub code. Strange.
Is this project still maintained? If yes, some help would be greatly appreciated for non-US users. Thanks in advance.

**Comment by chipx86** [comment]
I haven't disappeared entirely, but I also haven't had a need to use cloudplaya in a while (and my plate is quite full with a startup). So I haven't been actively maintaing it. I would be happy to have patches though.

**Comment by xiconet** [comment]
Sorry, no patch for the moment. Still haven't figured out how to make this work
